name: "Convert repository action"
description: "Get started with Python Container actions"
author: "Aurelien ROY"
inputs:
  repository:
    description: "Repository to convert"
    required: true
  odoo_id:
    description: "Odoo database ID"
    required: true
  github_token:
    description: "Github token"
    required: true
  odoo_host:
    description: "Odoo host"
    required: true
  odoo_database:
    description: "Odoo database"
    required: true
  odoo_user:
    description: "Odoo user"
    required: true
  odoo_password:
    description: "Odoo password"
    required: true
  odoo_token:
    description: "Odoo token"
    required: true
runs:
  using: "docker"
  # image: "Dockerfile"
  image: 'docker://ghcr.io/apikcloud/convert-repository-action:v1'